trigger:
  - main  # Déclenchement sur la branche principale

pool:
  vmImage: 'windows-latest'  # Image de l'agent

variables:
  azureSubscription: 'MyAzureConnection'  # Nom de la Service Connection dans Azure DevOps
  resourceGroupName: 'heumbia21'  # Nom du groupe de ressources Azure
  location: 'Canada Central'  # Emplacement des ressources Azure
  functionAppBlobTrigger: 'BlobTriggerFunction'  # Nom de l'Azure Function App pour BlobTriggerFunction
  functionAppBusFunction: 'BusFunction'  # Nom de l'Azure Function App pour BusFunction

steps:
  # Étape 1 : Déployer les ressources Azure avec les fichiers ARM
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Azure resources using ARM templates'
    inputs:
      azureResourceManagerConnection: $(azureSubscription)
      subscriptionId: '<644f8dda-724f-4ca4-bf35-d8131da4649b>'
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)/AzureFonction3/azuredeploy.json'  # Chemin vers fichier ARM
      csmParametersFile: '$(Build.SourcesDirectory)/AzureFonction3/azuredeploy.parameters.json'  # Chemin vers vos paramètres ARM

  # Étape 2 : Installons les dépendances .NET
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Étape 3 : Restaurons les packages NuGet pour BlobTriggerFunction
  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages for BlobTriggerFunction'
    inputs:
      restoreSolution: 'BlobTriggerFunction/BlobTriggerFunction.csproj'

  # Étape 4 : Construisons le projet BlobTriggerFunction
  - task: DotNetCoreCLI@2
    displayName: 'Build BlobTriggerFunction'
    inputs:
      command: 'build'
      projects: 'BlobTriggerFunction/BlobTriggerFunction.csproj'
      arguments: '--configuration Release'

  # Étape 5 : Publions les artefacts de BlobTriggerFunction
  - task: DotNetCoreCLI@2
    displayName: 'Publish BlobTriggerFunction'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'BlobTriggerFunction/BlobTriggerFunction.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/BlobTriggerFunction'
      modifyOutputPath: true

  # Étape 6 : Restaurons les packages NuGet pour BusFunction
  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages for BusFunction'
    inputs:
      restoreSolution: 'BusFunction/BusFunction.csproj'

  # Étape 7 : Construisons le projet BusFunction
  - task: DotNetCoreCLI@2
    displayName: 'Build BusFunction'
    inputs:
      command: 'build'
      projects: 'BusFunction/BusFunction.csproj'
      arguments: '--configuration Release'

  # Étape 8 : Publions les artefacts de BusFunction
  - task: DotNetCoreCLI@2
    displayName: 'Publish BusFunction'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'BusFunction/BusFunction.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/BusFunction'
      modifyOutputPath: true

  # Étape 9 : Déployons BlobTriggerFunction sur Azure
  - task: AzureFunctionApp@1
    displayName: 'Deploy BlobTriggerFunction'
    inputs:
      azureSubscription: $(azureSubscription)
      appType: 'functionApp'
      appName: $(functionAppBlobTrigger)
      package: '$(Build.ArtifactStagingDirectory)/BlobTriggerFunction'

  # Étape 10 : Déployons BusFunction sur Azure
  - task: AzureFunctionApp@1
    displayName: 'Deploy BusFunction'
    inputs:
      azureSubscription: $(azureSubscription)
      appType: 'functionApp'
      appName: $(functionAppBusFunction)
      package: '$(Build.ArtifactStagingDirectory)/BusFunction'

  # Étape 11 : Validons le déploiement des Function Apps
  - task: AzureCLI@2
    displayName: 'Validate Function Apps deployment'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp show --name $(functionAppBlobTrigger) --resource-group $(resourceGroupName)
        az functionapp show --name $(functionAppBusFunction) --resource-group $(resourceGroupName)
